argument_specs:
    main:
        options:
            infinispan_bind_address:
                # line 2 of infinispan_cache/defaults/main.yml
                default: "localhost"
                description: "Alternate bind address for the daemon"
                type: "str"
            infinispan_port:
                # line 3 of infinispan_cache/defaults/main.yml
                default: 11222
                description: "Alternate port for the service"
                type: "int"
            infinispan_tls:
                # line 4 of infinispan_cache/defaults/main.yml
                default: false
                description: "Server REST API/hotrod have TLS enabled"
                type: "bool"
            infinispan_deployer_user:
                # line 5 of infinispan_cache/defaults/main.yml
                default: "supervisor"
                description: "Username that performs the API call"
                type: "str"
            infinispan_cache_xml:
                # line 6 of infinispan_cache/defaults/main.yml
                default: ""
                description: "XML declaration for the cache to deploy as string"
                type: "str"
            infinispan_cache_config:
                # line 6 of infinispan_cache/defaults/main.yml
                default: "{}"
                description: "dict object with configuration for the cache to deploy"
                type: "dict"
            infinispan_deployer_password:
                # line 3 of infinispan_cache/vars/main.yml
                required: true
                description: "Password for the user performing the API call"
                type: "str"
            infinispan_rest_cache_api_path:
                # line 6 of infinispan_cache/vars/main.yml
                default: "/rest/v2/caches/"
                description: "Path of infinispan rest api"
                type: "str"
            infinispan_scheme:
                # line 7 of infinispan_cache/vars/main.yml
                default: "{{ 'https' if infinispan_tls else 'http' }}"
                description: "Choose rest api protocol"
                type: "str"
            infinispan_url:
                # line 8 of infinispan_cache/vars/main.yml
                default: "{{ infinispan_scheme }}://{{ infinispan_bind_address }}:{{ infinispan_port }}{{ infinispan_rest_cache_api_path }}"
                description: "Complete URL for connecting to infinispan rest api"
                type: "str"
