---
# Red Hat JDG specific config
jdg_version: "8.2.0"
jdg_default_installation_path: "/opt/redhat-datagrid-{{ jdg_version }}-server/"
jdg_bundle: "jdg-{{ jdg_version }}.zip"
jdg_download_url: 'https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId='

# Infinispan specific config
infinispan_version: "12.1.7.Final"
infinispan_bundle: "infinispan-server-{{ infinispan_version }}.zip"
infinispan_download_url: "https://downloads.jboss.org/infinispan/{{ infinispan_version }}/{{ infinispan_bundle }}"
infinispan_installation_path: "/opt/infinispan-server-{{ infinispan_version }}/"

# common config for datagrid/infinispan service
jdg_app_download_dir: "/opt/apps"
jdg_enable: "{{ True if jdg_rhn_id is defined else False }}"
jdg_healthcheck: True
jdg:
  home: "{{jdg_default_installation_path if jdg_rhn_id is defined else infinispan_installation_path }}"
  bind_addr: "{{ override_jdg_bind_addr | default('localhost') }}"
  port: "{{ override_jdg_port | default('11222') }}"
  jgroups_port: "7800"
  config:
    name: "{{ override_jdg_config | default('jdg.xml') }}"
    template: "{{ override_jdg_config_template | default('templates/infinispan.xml.j2') }}"
    users: "{{ override_jdg_config_users_properties | default('users.properties') }}"
    groups: "{{ override_jdg_config_group_properties | default('groups.properties') }}"
  user:
    name: "{{ override_jdg_user | default('jdg') }}"
  group:
    name: "{{ override_jdg_group | default('jdg') }}"
  service:
    name: "{{ override_jdg_service_name | default('jdg') }}"
  users: "{{ [ jdg_supervisor ] + infinispan_users|default([]) }}"

jdg_supervisor:
  name: 'supervisor'
  password: "{{ supervisor_password|default('itsme') }}"
  roles: 'supervisor'

jdg_default_realm_tls: False

jdg_keycloak_cache:
  enabled: "{{ create_keycloak_caches }}"
  caches:
    - sessions
    - offlineSessions
    - clientSessions
    - offlineClientSessions
    - loginFailures
    - actionTokens
    - work
