---
# Required variables
infinispan_deployer_password:

# Internal variables
infinispan_rest_cache_api_path: /rest/v2/caches/
infinispan_scheme: "{{ 'https' if infinispan_tls else 'http' }}"
infinispan_url: "{{ infinispan_scheme }}://{{ infinispan_bind_address }}:{{ infinispan_port }}{{ infinispan_rest_cache_api_path }}"
