---
- name: Converge
  hosts: all
  gather_facts: yes
  roles:
    - role: infinispan
      supervisor_password: "itsme"
      infinispan_users:
        - { name: 'testuser', password: 'test', roles: 'observer' }
      jdg_caches:
        - cache_xml: >
            <local-cache name="teststaticcachexml" statistics="true">
              <encoding media-type="application/x-protostream"/>
            </local-cache>
        - cache_config:
            name: configuredstaticcache
            template: replicated
            mode: ASYNC
    - role: infinispan
      jdg_nodename: instance2
      supervisor_password: "itsme2"
      jdg_port_offset: 100
      infinispan_installation_path: "/opt/infinispan-2/infinispan-server-{{ infinispan_version }}/"
      infinispan_users:
        - { name: 'testuser2', password: 'test2', roles: 'deployer' }
      jdg_caches:
        - cache_xml: >
            <local-cache name="teststaticcachexml" statistics="true">
              <encoding media-type="application/x-protostream"/>
            </local-cache>
        - cache_config:
            name: configuredstaticcache
            template: replicated
            mode: ASYNC
    - role: infinispan_cache
      deployer_user: "supervisor"
      deployer_password: "itsme"
      cache_xml: >
        <local-cache name="testcachexml" statistics="true">
          <encoding media-type="application/x-protostream"/>
        </local-cache>
    - role: infinispan_cache
      deployer_user: "supervisor"
      deployer_password: "itsme"
      cache_config:
        name: configuredcache
        template: replicated
        mode: ASYNC
        unreliable_return_values: true
        transaction_mode: NONE
        transaction_locking: PESSIMISTIC
        memory_max_size: '100000000'
        memory_when_full: 'REMOVE'
        expiration_lifespan: 60000
        expiration_max_idle: 10000
        persistence: false
        indexing: false
    - role: infinispan_cache
      deployer_user: "supervisor"
      deployer_password: "itsme"
      cache_config:
        name: configuredcachexa
        template: distributed
        mode: SYNC
        unreliable_return_values: true
        transaction_mode: FULL_XA
        transaction_locking: PESSIMISTIC
        memory_max_count: '1000'
        memory_when_full: 'REMOVE'
        expiration_lifespan: 600000
        expiration_max_idle: 30000
        persistence: false
        indexing: true
        indexing_entities:
          - org.infinispan.sample.Car
          - book_sample.Book
