---
- name: Converge
  hosts: all
  vars: 
    jdg_enable: False
    override_jdg_bind_address: "{{ ansible_nodename }}"
  tasks:
    - name: Include infinispan role
      include_role:
        name: ../../roles/infinispan
    - name: Create test cache
      include_role:
        name: ../../roles/infinispan
        tasks_from: cache.yml
      vars:
        jdg_url: "http://{{ jdg.bind_addr }}:{{ jdg.port }}"
        jdg_username: "{{ jdg.users[0].name }}"
        jdg_password: "{{ jdg.users[0].password }}"
        cache:
          name: test_cache