---
- name: Converge
  hosts: all
  vars: 
    jdg_enable: False
    override_jdg_bind_address: "{{ ansible_nodename }}"
  tasks:
    - name: Include infinispan role
      include_role:
        name: ../../roles/infinispan