---
- name: Converge
  hosts: all
  tasks:
    - name: Include infinispan role
      include_role:
        name: ../../roles/infinispan
      vars:
        supervisor_password: "itsme"
        infinispan_users:
          - { name: 'testuser', password: 'test', roles: 'observer' }
    - name: Create test cache
      include_role:
        name: ../../roles/infinispan
        tasks_from: cache.yml
      vars:
        jdg_url: "http://{{ jdg.bind_addr }}:{{ jdg.port }}"
        jdg_username: "supervisor"
        jdg_password: "itsme"
        cache:
          name: test_cache