---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Check if infinispan service started
      assert:
        that:
          - ansible_facts.services["infinispan.service"]["state"] == "running"
          - ansible_facts.services["infinispan.service"]["status"] == "enabled"
    - name: "Check service operational: create test cache via rest"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/test_cache
        method: POST
        url_username: "supervisor"
        url_password: "remembertochangeme"
        status_code:
          - 200
    - name: "Check service operational: add entry to test cache via rest"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/test_cache/test_entry
        method: POST
        url_username: "supervisor"
        url_password: "remembertochangeme"
        status_code: 
          - 204
    - name: "Check service operational: test cache status via rest"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/test_cache
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - assert:
        that:
          - test_cache_status.json.size == 1
        fail_msg: "infinispan operational error: test cache error"
    - name: "Check configuration: static test cache (xml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/teststaticcachexml
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.size == 0
        fail_msg: "infinispan config error: static test cache via XML error"
    - name: "Check configuration: static test cache (yml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/configuredstaticcache
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.size == 0
        fail_msg: "infinispan config error: static test cache via YML error"
    - name: "Check _cache role: test cache (xml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/testcachexml
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.size == 0
        fail_msg: "infinispan_cache error: test cache via XML error"
    - name: "Check _cache role: test cache (yml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/configuredcache
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.size == 0
        fail_msg: "infinispan_cache error: test cache via YML error"
    - name: "Check _cache role: test cache (yml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/configuredcachexa
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.size == 0
        fail_msg: "infinispan_cache error: test cache via YML error"