---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - cache is defined
      - cache.name is defined
      - jdg_url is defined
    quiet: true

- block:
    - name: Check cache state
      ansible.builtin.include_tasks: query_cache.yml
      vars:
        method: GET
  rescue:
    - name: Create cache
      ansible.builtin.include_tasks: query_cache.yml
      vars:
        method: POST
