---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - cache is defined
      - cache.name is defined
      - infinispan_url is defined
    quiet: true

- name: Check cache state and create if not existing
  block:
    - name: Check cache state
      ansible.builtin.include_tasks: query_cache.yml
      vars:
        method: GET
  rescue:
    - name: Create cache
      ansible.builtin.include_tasks: query_cache.yml
      vars:
        method: POST
