---
- name: Ensure required package firewalld is installed
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - firewalld

- name: Enable and start the firewalld service
  become: "{{ infinispan_install_requires_become | default(true) }}"
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: "Configure firewall for {{ infinispan.name }} ports"
  become: "{{ infinispan_install_requires_become | default(true) }}"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ infinispan.port }}/tcp"
    - "{{ infinispan.jgroups_port }}/tcp"
    - "{{ infinispan.jgroups_relay_port }}/tcp"
  notify:
    - Restart firewalld
