---
- name: "Create group {{ jdg.group.name }}"
  ansible.builtin.group:
    name: "{{ jdg.group.name }}"
    state: present
    gid: "{{ jdg.group.id | default(omit) }}"

- name: "Create user {{ jdg.user.name }}"
  ansible.builtin.user:
    name: "{{ jdg.user.name }}"
    state: present
    uid: "{{ jdg.user.id | default(omit) }}"

- name: "Create download directory"
  ansible.builtin.file:
    path: "{{ jdg_app_download_dir }}"
    state: directory
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0750

## check remote archive
- name: Set download archive path
  ansible.builtin.set_fact:
    archive: "{{ jdg_app_download_dir }}/{{ jdg.bundle }}"

- name: Check download archive path
  ansible.builtin.stat:
    path: "{{ archive }}"
  register: archive_path

- name: Check local download archive path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'PWD') }}"
  register: local_path
  delegate_to: localhost

## download to controller
- name: Download infinispan archive
  ansible.builtin.get_url:
    url: "{{ infinispan_download_url }}"
    dest: "{{ local_path.stat.path }}/{{ jdg.bundle }}"
  delegate_to: localhost
  when:
    - archive_path is defined
    - archive_path.stat is defined
    - not archive_path.stat.exists
    - not jdg_enable
    - not jdg_offline_install

- name: Perform download from RHN
  redhat_csp_download:
    url: "{{ jdg_download_url }}"
    dest: "{{ local_path.stat.path }}/{{ jdg.bundle }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  no_log: "{{ omit_rhn_output | default(true) }}"
  delegate_to: localhost
  when:
    - archive_path is defined
    - archive_path.stat is defined
    - not archive_path.stat.exists
    - jdg_enable
    - not jdg_offline_install
    - jdg_rhn_url in jdg_download_url

- name: Download DataGrid archive from alternate location
  ansible.builtin.get_url:
    url: "{{ jdg_download_url }}"
    dest: "{{ local_path.stat.path }}/{{ jdg.bundle }}"
  delegate_to: localhost
  when:
    - archive_path is defined
    - archive_path.stat is defined
    - not archive_path.stat.exists
    - jdg_enable
    - not jdg_offline_install
    - not jdg_rhn_url in jdg_download_url

- name: Check downloaded archive
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ jdg.bundle }}"
  register: local_archive_path
  delegate_to: localhost

## copy and unpack
- name: Copy archive to target nodes
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ jdg.bundle }}"
    dest: "{{ archive }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0750
  register: new_version_downloaded
  when:
    - not archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes

- name: "Check target directory: {{ jdg.installation_path }}"
  ansible.builtin.stat:
    path: "{{ jdg.installation_path }}"
  register: path_to_workdir
  become: yes

- name: "Extract {{ 'Red Hat Datagrid' if jdg_enable else 'Infinispan' }} archive on target {{ jdg.installation_path }}"
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ archive }}"
    dest: "{{ jdg_app_download_dir }}"
    creates: "{{ jdg.installation_path }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
  become: yes
  when:
    - new_version_downloaded.changed or not path_to_workdir.stat.exists
  notify:
    - restart infinispan

- name: Inform decompression was not executed
  ansible.builtin.debug:
    msg: "{{ jdg.installation_path }} already exists and version unchanged, skipping decompression"
  when:
    - not new_version_downloaded.changed and path_to_workdir.stat.exists

- name: "Reown installation directory to {{ jdg.user.name }}"
  ansible.builtin.file:
    path: "{{ jdg.home }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    recurse: true
  become: yes
  changed_when: false
