---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - users is defined
      - users | length > 0
    quiet: true

- name: "Ensure {{ jdg.config.users }} exists."
  ansible.builtin.template:
    src: templates/users.properties.j2
    dest: "{{ jdg.home }}/server/conf/{{ jdg.config.users }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0644
  notify:
    - restart infinispan

- name: "Ensure {{ jdg.config.groups }} exists"
  ansible.builtin.template:
    src: templates/groups.properties.j2
    dest: "{{ jdg.home }}/server/conf/{{ jdg.config.groups }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0644
  notify:
    - restart infinispan