---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - infinispan.home is defined
      - infinispan.user is defined
      - infinispan.user.name is defined
      - infinispan.group is defined
      - infinispan.group.name is defined
      - infinispan.version is defined
      - infinispan.config is defined
      - infinispan.config.name is defined
      - infinispan.service.name is defined
    quiet: true

- name: Install parameters
  ansible.builtin.debug:
    var: infinispan_installation_path

- name: Install parameters
  ansible.builtin.debug:
    var: infinispan

- name: Include prerequisite tasks
  ansible.builtin.include_tasks: prereqs.yml
  tags:
    - prereqs

- name: Include firewall config tasks
  ansible.builtin.include_tasks: firewalld.yml
  when: infinispan_configure_firewalld
  tags:
    - firewall

- name: Include install tasks
  ansible.builtin.include_tasks: tasks/install.yml
  tags:
    - install

- name: Install directory
  ansible.builtin.debug:
    msg: "{{ infinispan_service_desc }} installed at path {{ infinispan.home }}"

- name: Include systemd tasks
  ansible.builtin.include_tasks: tasks/systemd.yml
  tags:
    - systemd

- name: Create infinispan cluster node members
  ansible.builtin.set_fact:
    infinispan_cluster_nodes: >
      {{ infinispan_cluster_nodes | default([]) + [
           {
             "name": item,
             "site": host_site,
             "address": host_address,
             "inventory_host": host_address + '[' + host_port + ']',
             "port": host_port,
             "value": "tcp://" + host_address + ":" + host_port
           }
         ] }}
  loop: "{{ ansible_play_batch }}"
  vars:
    host_iface: "{{ 'ansible_' + infinispan_jgroups_iface }}"
    host_address: "{{ hostvars[item][host_iface]['address'] | \
                      default(hostvars[item][host_iface]['ipv4']['address'] | \
                      default(hostvars[item]['ansible_host']) | \
                      default(hostvars[item]['inventory_hostname_short'])) }}"
    host_port: "{{ (((infinispan_jgroups_port | int + infinispan_port_offset | int) | abs) | string) }}"
    host_site: "{{ hostvars[item]['infinispan_jgroups_relay_site'] | default(infinispan_jgroups_relay_site) if infinispan_jgroups_relay else '' }}"
  when:
    - infinispan_jgroups_cluster_nodes | length == 0
    - infinispan_jgroups_discovery == 'TCPPING'

- name: Create infinispan cluster node members
  ansible.builtin.set_fact:
    infinispan_cluster_nodes: "{{ infinispan_jgroups_cluster_nodes }}"
  when:
    - infinispan_jgroups_cluster_nodes | length > 0
    - infinispan_jgroups_discovery == 'TCPPING'

- name: Determine JAVA_HOME for selected JVM RPM
  ansible.builtin.set_fact:
    rpm_java_home: "/etc/alternatives/jre_{{ infinispan_jvm_package | regex_search('(?<=java-)[0-9.]+') }}"

- name: "Ensure {{ infinispan.service.name }} service configuration is deployed: server.conf"
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ infinispan.home }}/bin/server.conf"
    owner: "{{ infinispan.user.name }}"
    group: "{{ infinispan.group.name }}"
    mode: '0644'
    backup: true
  vars:
    jdg_rpm_java_home: "{{ rpm_java_home }}"
  notify:
    - restart infinispan
  become: "{{ infinispan_install_requires_become | default(true) }}"

- name: "Get xsd schema versions"
  ansible.builtin.find:
    paths: "{{ infinispan.home }}/docs/schema/"
    use_regex: true
    patterns: ['^.*-server-[0-9.]*[.]xsd$']
  register: server_schema
  become: "{{ infinispan_install_requires_become | default(true) }}"

- name: "Set fetched schema version for template"
  ansible.builtin.set_fact:
    schema_version: "{{ server_schema.files | first | regex_search('[0-9.]*(?=.xsd)') }}"

- name: "Ensure {{ infinispan.service.name }} server configuration is deployed: {{ infinispan.config.name }}"
  ansible.builtin.template:
    src: "{{ infinispan.config.template }}"
    dest: "{{ infinispan.home }}/server/conf/{{ infinispan.config.name }}"
    owner: "{{ infinispan.user.name }}"
    group: "{{ infinispan.group.name }}"
    mode: '0644'
    backup: true
  notify:
    - restart infinispan
  become: "{{ infinispan_install_requires_become | default(true) }}"

- name: "Ensure {{ infinispan.service.name }} log4j2 configuration is deployed"
  ansible.builtin.template:
    src: log4j2.xml.j2
    dest: "{{ infinispan.home }}/server/conf/log4j2.xml"
    owner: "{{ infinispan.user.name }}"
    group: "{{ infinispan.group.name }}"
    mode: '0644'
    backup: true
  notify:
    - restart infinispan
  become: "{{ infinispan_install_requires_become | default(true) }}"

- name: Download database driver jar to target
  ansible.builtin.get_url:
    url: "{{ infinispan_jgroups_jdbc[infinispan_jdbc_engine].driver_jar_url }}"
    dest: "{{ infinispan.home }}/lib/{{ infinispan_jgroups_jdbc[infinispan_jdbc_engine].driver_jar_filename }}"
    owner: "{{ infinispan.user.name }}"
    group: "{{ infinispan.group.name }}"
    mode: '0644'
  when:
    - infinispan_jgroups_discovery == 'JDBC_PING'
  become: "{{ infinispan_install_requires_become | default(true) }}"

- name: Include users tasks
  ansible.builtin.include_tasks: jdg_user.yml
  vars:
    users: "{{ infinispan.users }}"
  when:
    - infinispan.users is defined
    - infinispan.users | length > 0

- name: "Ensure {{ infinispan.service.name }} service is running and enabled (first node)"
  ansible.builtin.include_tasks: start.yml
  run_once: true
  when: infinispan_jgroups_discovery == 'JDBC_PING' or infinispan_keycloak_persistence

- name: "Ensure {{ infinispan.service.name }} service is running and enabled (all nodes)"
  ansible.builtin.include_tasks: start.yml

- name: Link default logs directory
  ansible.builtin.file:
    state: link
    src: "{{ infinispan.home }}server/log"
    dest: "/var/log/infinispan{{ '-' + infinispan_nodename if infinispan_nodename != inventory_hostname else '' }}"
    force: true
  become: "{{ infinispan_install_requires_become | default(true) }}"
