---
- assert:
    that:
      - jdg is defined
      - jdg.home is defined
      - jdg.user is defined
      - jdg.user.name is defined
      - jdg.group is defined
      - jdg.group.name is defined
      - jdg_version is defined
    quiet: true

- include_tasks: prereqs.yml

- name: "Create group {{ jdg.group.name }}"
  group:
    name: "{{ jdg.group.name }}"
    state: present
    gid: "{{ jdg.group.id | default(omit) }}"

- name: "Create user {{ jdg.user.name }}"
  user:
    name: "{{ jdg.user.name }}"
    state: present
    uid: "{{ jdg.user.id | default(omit) }}"

- name: "Create download directory"
  file:
    path: "{{ jdg_app_download_dir }}"
    state: directory
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0750

- include_tasks: tasks/install.yml

- debug:
    msg: "{{ 'Red Hat Datagrid' if jdg_rhn_id is defined else 'Infinispan' }} installed at path {{ jdg.home }}"

- name: "Configure systemd unit file for JDG service"
  template:
    src: templates/infinispan.service.j2
    dest: /etc/systemd/system/jdg.service
    owner: root
    group: root
    mode: 0644
  register: jdg_daemon_reload
  notify:
    - restart infinispan

- name: "Perform daemon-reload to ensure the changes on jdg service are picked up"
  systemd:
    daemon_reload: yes
  when:
    - jdg_daemon_reload is defined
    - jdg_daemon_reload.changed

- name: "Ensures JDG configuration is deployed: {{ jdg.config.name }}"
  template:
    src: "{{ jdg.config.template }}"
    dest: "{{ jdg.home }}/server/conf/{{ jdg.config.name }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0644
    backup: yes
  when:
    - jdg.config is defined
    - jdg.config.name is defined
  notify:
    - restart infinispan

- include_tasks: jdg_user.yml
  vars:
    users: "{{ jdg.users }}"
  when:
    - jdg.users is defined
    - jdg.users | length > 0

- name: Ensures JDG service is running and enabled
  systemd:
    name: jdg
    state: started
    enabled: yes

- meta: flush_handlers

- name: "Wait for all used ports to be open"
  wait_for:
    port: "{{ jdg.port }}"
    delay: 0
  when:
    - jdg_healthcheck
    - jdg.port is defined

- name: Create keycloak remote caches
  include_tasks: keycloak.yml
  when:
    - jdg_keycloak_cache.enabled

- name: "Check keycloak remote caches"
  include_tasks: query_cache.yml
  vars:
    jdg_url: "http://{{ jdg.bind_addr }}:{{ jdg.port }}"
    jdg_username: "{{ jdg_supervisor.name }}"
    jdg_password: "{{ jdg_supervisor.password }}"
    method: GET
    cache:
      name: sessions
  when:
    - jdg_healthcheck
    - jdg_keycloak_cache.enabled