---
- assert:
    that:
      - jdg is defined
      - jdg.home is defined
      - jdg.user is defined
      - jdg.user.name is defined
      - jdg.group is defined
      - jdg.group.name is defined
      - jdg.version is defined
      - supervisor_password is defined and supervisor_password|length > 0
    quiet: true

- include_tasks: prereqs.yml

- name: "Create group {{ jdg.group.name }}"
  group:
    name: "{{ jdg.group.name }}"
    state: present
    gid: "{{ jdg.group.id | default(omit) }}"

- name: "Create user {{ jdg.user.name }}"
  user:
    name: "{{ jdg.user.name }}"
    state: present
    uid: "{{ jdg.user.id | default(omit) }}"

- name: "Create download directory"
  file:
    path: "{{ jdg_app_download_dir }}"
    state: directory
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0750

- include_tasks: tasks/install.yml

- debug:
    msg: "{{ 'Red Hat Datagrid' if jdg_rhn_id is defined else 'Infinispan' }} installed at path {{ jdg.home }}"

- include_tasks: tasks/systemd.yml

- name: "Ensures {{ jdg.service.name }} configuration is deployed: {{ jdg.config.name }}"
  template:
    src: "{{ jdg.config.template }}"
    dest: "{{ jdg.home }}/server/conf/{{ jdg.config.name }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0644
    backup: yes
  when:
    - jdg.config is defined
    - jdg.config.name is defined
    - jdg.service.name is defined
  notify:
    - restart infinispan

- name: "Ensures {{ jdg.service.name }} jgroups configuration is deployed"
  template:
    src: "{{ jdg.config.jgroups_template }}"
    dest: "{{ jdg.home }}/server/conf/jgroups-jdbcping.xml"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0644
  when:
    - jdg.config is defined
    - jdg.config.name is defined
    - jdg.service.name is defined
    - jdg_jgroups_jdbcping
  notify:
    - restart infinispan

- name: Download mariadb driver jar to target
  get_url:
    url: "{{ jdg_jgroups_jdbc.mariadb.driver_jar_url }}"
    dest: "{{ jdg.home }}/lib/{{ jdg_jgroups_jdbc.mariadb.driver_jar_filename }}"
    owner: "{{ jdg.user.name }}"
    group: "{{ jdg.group.name }}"
    mode: 0644
  when:
    - jdg.config is defined
    - jdg_jgroups_jdbcping

- include_tasks: jdg_user.yml
  vars:
    users: "{{ jdg.users }}"
  when:
    - jdg.users is defined
    - jdg.users | length > 0

- name: "Ensures {{ jdg.service.name }} service is running and enabled"
  systemd:
    name: "{{ jdg.service.name }}"
    state: started
    enabled: yes

- meta: flush_handlers

- name: "Wait for all used ports to be open"
  wait_for:
    port: "{{ jdg.port }}"
    delay: 0
  when:
    - jdg_healthcheck
    - jdg.port is defined

- name: Create keycloak remote caches
  include_tasks: keycloak.yml
  when:
    - jdg_keycloak_cache.enabled
