---
- name: Validate credentials
  ansible.builtin.assert:
    that:
      - (rhn_username is defined and jdg_enable is defined and jdg_enable) or not jdg_enable is defined or not jdg_enable or infinispan_offline_install
      - (rhn_password is defined and jdg_enable is defined and jdg_enable) or not jdg_enable is defined or not jdg_enable or infinispan_offline_install
    quiet: True
    fail_msg: "Cannot install {{ infinispan.name }} without RHN credentials. Check rhn_username and rhn_password are defined"
    success_msg: "Installing {{ infinispan_service_desc }}"

- name: Validate admin console password
  ansible.builtin.assert:
    that:
      - infinispan_supervisor_password | length > 12
    quiet: True
    fail_msg: "The console administrator password is empty or invalid. Please set the infinispan_supervisor_password variable to a 12+ char long string"
    success_msg: "{{ 'Console administrator password OK' }}"

- name: Ensure required packages are installed
  ansible.builtin.include_tasks: fastpackages/install.yml
  vars:
    packages_list:
      - unzip
      - procps-ng
      - initscripts
      - "{{ infinispan_jvm_package }}"
