---
- name: Validate credentials
  ansible.builtin.assert:
    that:
      - (rhn_username is defined and jdg_enable) or not jdg_enable or jdg_offline_install
      - (rhn_password is defined and jdg_enable) or not jdg_enable or jdg_offline_install
    quiet: True
    fail_msg: "Cannot install {{ jdg.name }} without RHN credentials. Check rhn_username and rhn_password are defined"
    success_msg: "{{ 'Installing Red Hat DataGrid' if jdg_enable else 'Installing Infinispan' }}"

- name: Validate admin console password
  ansible.builtin.assert:
    that:
      - supervisor_password | length > 12
    quiet: True
    fail_msg: "The console administrator password is empty or invalid. Please set the supervisor_password variable to a 16+ char long string"
    success_msg: "{{ 'Console administrator password OK' }}"

- name: Set required packages facts
  ansible.builtin.set_fact:
    required_packages:
    - unzip
    - procps-ng
    - initscripts
    - "{{ jdg_jvm_package }}"

- name: Ensure required packages are installed
  ansible.builtin.include_tasks: fastpackages/install.yml
  vars:
    packages_list: "{{ required_packages }}"
