---
- set_fact:
    required_packages:
    - zip
    - unzip
    - procps-ng
    - initscripts
    - "{{ jvm_package | default('java-1.8.0-openjdk-devel') }}"

- name: "Ensures required packages are installed"
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list: "{{ required_packages }}"
