---
- throttle: 1
  block:
  - name: "Restart service"
    ansible.builtin.systemd:
      name: "{{ jdg.service.unit_file }}"
      state: restarted  
  - name: "Wait for used port to be open"
    ansible.builtin.wait_for:
      port: "{{ jdg.port }}"
      delay: 0
    when:
      - jdg_healthcheck
