- name: "Configure systemd unit file for {{ jdg.service.name }} service"
  template:
    src: templates/infinispan.service.j2
    dest: "/etc/systemd/system/{{ jdg.service.name }}.service"
    owner: root
    group: root
    mode: 0644
  register: jdg_daemon_reload
  notify:
    - restart infinispan

- name: "Perform daemon-reload to ensure the changes on {{ jdg.service.name }} service are picked up"
  systemd:
    daemon_reload: yes
  when:
    - jdg_daemon_reload is defined
    - jdg_daemon_reload.changed