---
- name: Playbook for infinispan Hosts
  hosts: all
  become: yes
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - role: redhat_csp_download
    - role: infinispan
      supervisor_password: "itsme"
      infinispan_users: []
    - role: infinispan_cache
      deployer_user: "supervisor"
      deployer_password: "itsme"
      cache_xml: >
        <local-cache name="testcache" statistics="true">
          <encoding media-type="application/x-protostream"/>
        </local-cache>