---
collections:
  - middleware_automation.common
  - ansible.posix

galaxy_info:
  role_name: infinispan
  namespace: middleware_automation
  author: Romain Pelisse, Guido Grazioli
  description: Install and configure an Infinispan or DataGrid service.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - infinispan
    - datagrid
    - redhat
    - rhel
    - rhn
    - server
    - cache
