---
supervisor_password:
infinispan_users: []

jdg_supervisor:
  name: 'supervisor'
  password: "{{ supervisor_password }}"
  roles: 'admin'

jdg:
  home: "{{ jdg_default_installation_path if jdg_rhn_id is defined else infinispan_installation_path }}"
  version: "{{ jdg_version if jdg_rhn_id is defined else infinispan_version }}"
  bind_addr: "{{ jdg_bind_address }}"
  port: "{{ jdg_port }}"
  jgroups_bind_addr: "{{ override_jdg_jgroups_bind_addr | default('127.0.0.1') }}"
  jgroups_port: "{{ jdg_jgroups_port }}"
  jgroups_relay_port: "{{ jdg_jgroups_relay_port }}"
  config:
    name: "{{ override_jdg_config | default('jdg.xml') }}"
    template: "{{ override_jdg_config_template | default('templates/infinispan.xml.j2') }}"
    jgroups_template: "{{ override_jdg_config_jgroups_template | default('templates/jgroups-jdbcping.xml.j2') }}"
    users: "{{ override_jdg_config_users_properties | default('users.properties') }}"
    groups: "{{ override_jdg_config_group_properties | default('groups.properties') }}"
  user:
    name: "{{ jdg_service_user }}"
  group:
    name: "{{ jdg_service_group }}"
  service:
    name: "{{ override_jdg_service_name | default('jdg' if jdg_rhn_id is defined else 'infinispan') }}"
  users: "{{ [ jdg_supervisor ] + infinispan_users }}"

jdg_jgroups_jdbc:
  mariadb:
    enabled: "{{ jdg_jgroups_jdbcping and jdg_jdbc_engine == 'mariadb' }}"
    driver_class: org.mariadb.jdbc.Driver
    driver_jar_filename: "mariadb-java-client-2.7.4.jar"
    driver_jar_url: "https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/2.7.4/mariadb-java-client-2.7.4.jar"
    connection_url: "{{ jdg_jdbc_url | default('jdbc:mariadb://localhost:3306/keycloak') }}"
    db_user: "{{ jdg_jdbc_user }}"
    db_password: "{{ jdg_jdbc_pass }}"
    initialize_sql: >
      CREATE TABLE IF NOT EXISTS JGROUPSPING (
        own_addr varchar(200) NOT NULL,
        cluster_name varchar(200) NOT NULL,
        updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        ping_data varbinary(5000) DEFAULT NULL,
        PRIMARY KEY (own_addr, cluster_name))
      ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
  postgres:
    enabled: "{{ jdg_jgroups_jdbcping and jdg_jdbc_engine == 'postgres' }}"
    driver_class: org.postgresql.Driver
    driver_jar_filename: "postgresql-9.4.1212.jar"
    driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/9.4.1212/postgresql-9.4.1212.jar"
    connection_url: "{{ jdg_jdbc_url | default('jdbc:postgresql://localhost:5432/keycloak') }}"
    db_user: "{{ jdg_jdbc_user }}"
    db_password: "{{ jdg_jdbc_pass }}"
    initialize_sql: >
      CREATE TABLE IF NOT EXISTS JGROUPSPING (
        own_addr varchar(200) NOT NULL,
        cluster_name varchar(200) NOT NULL,
        updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ping_data BYTEA,
        constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))

jdg_keycloak_cache:
  enabled: "{{ infinispan_keycloak_caches }}"
  caches:
    - sessions
    - offlineSessions
    - clientSessions
    - offlineClientSessions
    - loginFailures
    - actionTokens
