---
name: Documentation
"on":
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

permissions:
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/middleware_automation/infinispan

      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        working-directory: ansible_collections/middleware_automation/infinispan/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ansible_collections/middleware_automation/infinispan/docs/requirements.txt
          pip install -r ansible_collections/middleware_automation/infinispan/requirements.txt

      - name: Create default collection path
        run: |
          mkdir -p /home/runner/.ansible/collections/ansible_collections

      - name: Create doc directories and resources
        run: |
          mkdir -p ./docs/plugins ./docs/roles
          cat ./docs/roles.rst.template > ./docs/roles/index.rst
          antsibull-docs collection --use-current --squash-hierarchy --dest-dir docs/plugins  middleware_automation.infinispan
          for role_readme in roles/*/README.md; do ln -f -s ../../$role_readme ./docs/roles/$(basename $(dirname $role_readme)).md; echo " * :doc:\`$(basename $(dirname $role_readme))\`" >> ./docs/roles/index.rst; done
        working-directory: ansible_collections/middleware_automation/infinispan

      - name: Run sphinx
        run: |
          sphinx-build -M html . _build -v
        working-directory: ansible_collections/middleware_automation/infinispan/docs/

      - name: Commit docs
        run: |
          git checkout gh-pages
          rm -rf $(basename ${GITHUB_REF})
          mv docs/_build/html $(basename ${GITHUB_REF})
          ln --force --no-dereference --symbolic  $(dirname *.*.*/index.html | sort --version-sort --reverse | head -n1) latest
          #git show origin/develop:docs/_gh_include/header.inc > index.html
          (echo echo latest; dirname *.*.*/index.html | sort --version-sort --reverse) | xargs -I@@ -n1 echo '<div class="col-md-4 center"><a href="@@/" class="btn-doc btn"><i class="fa fa-newspaper-o"></i><p>@@</p></a></div>' >> index.html
          #git show origin/:docs/_gh_include/footer.inc >> index.html
          git add $(basename ${GITHUB_REF}) latest index.html
          git commit -m "Update docs for $(basename ${GITHUB_REF})" || true
          git push
        working-directory: ansible_collections/middleware_automation/infinispan/

          #      - name: Push to destination branch
          #        uses: ad-m/github-push-action@v0.5.0
          #        with:
          #          github_token: ${{ secrets.GITHUB_TOKEN }}
          #          branch: gh-pages
          #          directory: ./ansible_collections/middleware_automation/infinispan/
